### ISSUE TITLE
Ion images do not look good after proprocessing

### ISSUE THREAD

**Issue by ranabanik** [fgrelard/Esmraldi#1] opened 2022-07-26 20:11 UTC
I used the following preprocessing params: 
```
    fac = 15000
    nl = 2
    wl = 100
    peakmzs = sp.spectra_peak_mzs_adaptative_noiselevel(spectra, factor=fac, noise_level=nl, wlen=wl)  # noise_level=1,
    realigned_spectra, aligned_mzs = np.array(sp.realign_mzs(spectra, peakmzs, reference="median", nb_occurrence=4, step=0.01))
```

But when I visualize the ion images per m/z channel, they seem distorted: 

![image](https://user-images.githubusercontent.com/47092529/181102723-3b27e967-4f18-48f3-b4ce-ffff8a20764f.png)

Whereas using some other preprocessing method they look: 
![image](https://user-images.githubusercontent.com/47092529/181103179-de7027c0-1313-4879-b930-19ed7a553825.png)

you can see the detail in the anatomical tissue(butterfly shape and surrounding area)

Is there anything else I am missing?

**Comment by fgrelard** [comment] 2022-08-12 12:53
Thanks for raising this issue @ranabanik.

I suspect the issue comes from the way you are building the image from the spectra, although I cannot say for sure from your code snippet. Could you include the code for the part where you generate the image? Do you export it in imzML?

I am not able to reproduce the issue from my datasets. Would you be able to share your dataset?

**Comment by ranabanik** [comment] 2022-08-15 15:10
Hi, the issue comes from the way I built the images. you are right. I figured it out and wanted to delete the issue.

**Comment by fgrelard** [comment] 2022-08-16 09:42
Perfect, I am glad the issue is fixed. 

Closing.

**Closed as completed by fgrelard** 2022-08-16 09:42 UTC
